#!/bin/bash -e

basedir=$(cd $(dirname $0) && pwd)
tmpdir=$(mktemp -d)
qemu=/opt/qemu-rpi/bin/qemu-system-arm
fdisk=/sbin/sfdisk
machine=raspi
rpimount=$basedir/rpimount

function _cleanup {
    mount | grep -q $tmpdir/boot && \
	umount $tmpdir/boot || true
    mount | grep -q $tmpdir && \
	umount $tmpdir || true
    rm -rf $tmpdir
}

function _usage {
    echo "Usage: $0 [-r] /path/to/image"
}

trap _cleanup EXIT

if test `id -u` != 0; then
    sudo $0 $*
    exit 0
fi

if test $# -lt 1; then
    _usage
    exit 1
fi

opts=""
while getopts ":r" opt; do
    case $opt in
	r)
	    opts="$opts init=/bin/bash"
	    shift $((OPTIND-1))
	    ;;
	h)
	    _usage
	    exit 0
	    ;;
	\?)
	    _usage
	    exit 1
	    ;;
    esac
done

image=$1
if test ! -e $image; then
    echo "E: unknown image file " $image
    exit 1
fi

$rpimount $image $tmpdir

kernel=$tmpdir/boot/kernel.img
#kernel=/home/jean/BA_Projets/git/linux/vmlinux

$qemu \
    -kernel $kernel \
    -cpu arm1176 \
    -m 256 \
    -machine $machine \
    -no-reboot \
    -serial stdio \
    -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw $opts" \
    -drive file=$image,if=sd,cache=unsafe,format=raw
